# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
defaults: &defaults
  #### TEMPLATE_NOTE: go expects specific checkout path representing url
  #### expecting it in the form of
  ####   /go/src/github.com/circleci/go-tool
  ####   /go/src/bitbucket.org/circleci/go-tool
  working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}

version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: "circleci/golang:1.10"

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    <<: *defaults
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      # 'go get' only pulls from master branch, and circleci doesn't support dep
      - run: go get -v -t -d ./...
      - run: go vet -tests=false ./...
      - run: go test -v ./...
      - run: mkdir build
      - run: go build -v -o build/aws-runas

      - persist_to_workspace:
          root: build
          paths: aws-runas

  test:
    docker:
      - image: "circleci/ruby:2.5-stretch"

    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: build

      -run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      -run: mkdir -p /var/tmp/rspec
      -run:
        command: bundle exec rspec
        when: always
      - store_test_results:
          path: /var/tmp/rspec

workflows:
  version: 2

  build_and_test:
    jobs:
      - build
      - test
        requires:
          - build